"""Inspect every downloaded raw data file and write a readable summary.

For each file under data/raw/ this prints (and writes to
docs/data_inventory.md):
  - sheet names (xlsx) or "csv" for csv files
  - number of rows per sheet
  - column names
  - first 3 rows

Usage:
    uv run python scripts/inspect_raw.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

PROJECT_ROOT = Path(__file__).resolve().parents[1]
RAW_DIR = PROJECT_ROOT / "data" / "raw"
OUTPUT_PATH = PROJECT_ROOT / "docs" / "data_inventory.md"


def inspect_xlsx(path: Path) -> list[str]:
    lines = []
    sheets = pd.read_excel(path, sheet_name=None)
    lines.append(f"- sheets: {len(sheets)} -> {', '.join(sheets.keys())}")
    for sheet_name, df in sheets.items():
        lines.append(f"\n  **sheet `{sheet_name}`** - {len(df)} rows, {len(df.columns)} columns")
        lines.append(f"  columns: {list(df.columns)}")
        lines.append("\n  first 3 rows:\n")
        lines.append(_df_to_markdown(df.head(3)))
    return lines


def inspect_csv(path: Path) -> list[str]:
    lines = []
    df = pd.read_csv(path)
    lines.append("- sheets: csv (single table)")
    lines.append(f"\n  **table** - {len(df)} rows, {len(df.columns)} columns")
    lines.append(f"  columns: {list(df.columns)}")
    lines.append("\n  first 3 rows:\n")
    lines.append(_df_to_markdown(df.head(3)))
    return lines


def _df_to_markdown(df: pd.DataFrame) -> str:
    try:
        return df.to_markdown(index=False)
    except ImportError:
        # tabulate not installed - fall back to a plain repr
        return "```\n" + df.to_string(index=False) + "\n```"


def main() -> int:
    files = sorted(RAW_DIR.rglob("*.xlsx")) + sorted(RAW_DIR.rglob("*.csv"))
    if not files:
        print(f"No raw files found under {RAW_DIR}. Run src/data/ingest.py first.", file=sys.stderr)
        return 1

    report_lines = ["# Data Inventory", "", "Auto-generated by `scripts/inspect_raw.py`. Do not edit by hand.", ""]
    columns_by_file: dict[str, list] = {}

    for path in files:
        rel = path.relative_to(PROJECT_ROOT)
        print(f"Inspecting {rel} ...")
        report_lines.append(f"## `{rel}`")
        report_lines.append("")
        try:
            if path.suffix == ".xlsx":
                lines = inspect_xlsx(path)
                # record columns of the first sheet for cross-year comparison
                first_sheet_cols = list(pd.read_excel(path, sheet_name=0, nrows=0).columns)
                columns_by_file[str(rel)] = first_sheet_cols
            else:
                lines = inspect_csv(path)
                columns_by_file[str(rel)] = list(pd.read_csv(path, nrows=0).columns)
        except Exception as exc:  # noqa: BLE001 - surface any read failure in the report
            lines = [f"- ERROR reading file: {exc}"]
            print(f"  ERROR: {exc}", file=sys.stderr)
        report_lines.extend(lines)
        report_lines.append("")

    # Note column differences across the yearly historical files.
    historical = {k: v for k, v in columns_by_file.items() if "historical/" in k}
    if historical:
        report_lines.append("## Column differences across historical years")
        report_lines.append("")
        reference_name, reference_cols = next(iter(historical.items()))
        report_lines.append(f"Reference columns (from `{reference_name}`): {reference_cols}")
        report_lines.append("")
        any_diff = False
        for name, cols in historical.items():
            if cols != reference_cols:
                any_diff = True
                report_lines.append(f"- `{name}` differs: {cols}")
        if not any_diff:
            report_lines.append("- No differences found: all historical years share the same column names.")
        report_lines.append("")

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text("\n".join(report_lines))
    print(f"\nWrote summary to {OUTPUT_PATH.relative_to(PROJECT_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
